# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 11:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(db_index=True, editable=False, verbose_name='last updated at')),
                ('nick_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('date_created', models.DateField()),
                ('date_updated', models.DateField()),
                ('gender', models.CharField(choices=[(b'ml', b'Male'), (b'ml', b'Female'), (b'tr', b'Transsexual')], max_length=5)),
                ('about', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(db_index=True, editable=False, verbose_name='last updated at')),
                ('description', models.CharField(max_length=255)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='core.Profile')),
                ('profile', models.ManyToManyField(to='core.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
